#!/usr/bin/env bash


#
# NAVIGATE TO CORRECT DIRECTORY
#

# start by going to script dir so all movements
# from here are relative
SCRIPT_DIR=`dirname $(realpath "$0")`
cd $SCRIPT_DIR


function check {
    cd ..
    # enable app virtual environment
    eval "$(direnv export bash)"
    if [ !$PYTHONPATH ]; then
        export PYTHONPATH=$PWD
    fi
    echo ""

    echo ""
    echo "Starting type checks..."
    echo ""

    # tell mypy where the project root is for module resolution
    # FIXME: somehow mypy isnt picking up that MYPYPATH is set, but this
    # works when typed manually in bash shell
    # export MYPYPATH=$PWD,$PWD/stubs
    echo "PYTHONPATH: $PYTHONPATH"
    # echo "MYPYPATH: $MYPYPATH"

    echo "Checking ./src..."
    echo ""
    mypy src
    mypy_src_result=$?

    if [ $mypy_src_result != 0 ]; then
        echo "Error in typechecking, see output above."
        exit $mypy_src_result
    fi


    echo ""
    echo "Checking ./test/unit..."
    echo ""
    mypy test/unit
    mypy_tests_result=$?

    if [ $mypy_tests_result != 0 ]; then
        echo "Error in typechecking, see output above."
        exit $mypy_tests_result
    fi


    echo ""
    echo "Checking ./test/integration..."
    echo ""
    mypy test/integration
    mypy_tests_result=$?

    if [ $mypy_tests_result != 0 ]; then
        echo "Error in typechecking, see output above."
        exit $mypy_tests_result
    fi


    # return to scripts directory
    cd $SCRIPT_DIR
    echo ""
}

check
